org.gradle.jvmargs = -Xmx4096m

javaVersion = 21

# Mod properties
group               = com.ruslan.growsseth
archives_base_name  = ruins-of-growsseth
modid               = growsseth
modVersion          = 0.12.0dev

modName            = Ruins of Growsseth
modIcon            = assets/growsseth/icon.png
author             = Ruslan Fanclub
license            = MIT
displayUrl         = ""

# Settings
cydoVersion = false
includeDeps = false
# easier to disable during dev and enable via -PreplaceTokens=true
# during build to avoid issues
replaceTokens = false

#Dependencies
useLocalJarFilloaxLib = false
alwaysUseLocalMavenFilloaxLib = false