org.gradle.jvmargs = -Xmx4096m
org.gradle.parallel = true

javaVersion = 21

# Mod properties
group               = com.ruslan.growsseth
archives_base_name  = ruins-of-growsseth
modid               = growsseth
modVersion          = 0.13.2

# not required to be filled (alpha, beta, dev)
versionType        = beta

modName            = Ruins of Growsseth
modIcon            = assets/growsseth/icon.png
author             = Ruslan Fanclub
license            = MIT
displayUrl         = ""

# Settings
cydoVersion = false
includeDeps = false
# easier to disable during dev and enable via -PreplaceTokens=true
# during build to avoid issues
replaceTokens = false

# Dependencies
useLocalJarFilloaxLib = false
alwaysUseLocalMavenFilloaxLib = false


# Dokka plugin V2 config
org.jetbrains.dokka.experimental.gradle.pluginMode = V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn = true
