[versions]
java = "21"

# Minecraft dependencies
minecraft-range = "1.21.11"
minecraft-range-fabric = "1.21.11"
minecraft = "1.21.11"
# Get versions from https://parchmentmc.org/docs/getting-started
parchment-minecraft = "1.21.11"
parchment = "2025.12.20"
# Get versions from https://projects.neoforged.net/neoforged/neoform
neoform = "1.21.11-20251209.172050" # vanilla neoforge configuration

# Mod dependencies
filloaxlib = "0.36.0-1.21.11"
modmenu = "17.0.0-beta.1"
rconfig = "3.11.2"   # higher versions are not found with current settings (todo: fix)
rconfigMc = "1.21.11"

# Mod compatibility dependencies (todo: re-enabled if needed after 26.1 transition)
lithostitched-neoforge = "1.5.0-neoforge-1.21.1"
lithostitched-fabric = "1.5.0-fabric-1.21.1"
cobblemon = "1.7.1+1.21.1"
rctapi = "1.21.1-0.14.4" # only used for prop replacement in mod json files
rctapi-neoforge = "7257753"
rctapi-fabric = "7257754"
megashowdown = "1.4.4+1.7.1+1.21.1" # only used for prop replacement in mod json files

# Kotlin
kotlin = "2.3.0"
kotlin-serialization = "1.9.0"
kotlin-datetime = "0.7.1"

# Fabric Settings
# Get versions from https://github.com/FabricMC/fabric-loader/releases
fabric = "0.18.4"
# Get versions from https://modrinth.com/mod/fabric-api/versions
fabric-api = "0.140.2+1.21.11"
fabric-language-kotlin = "1.13.8+kotlin.2.3.0"

# Neoforge Settings
# Get versions from https://projects.neoforged.net/neoforged/neoforge
neoforge = "21.11.19-beta"
neoforge-range = "[21.11.19-beta,21.12)"
kotlinforge = "5.10.0"
kotlinforge-range = "[5.10,)"

# Other dependencies
mixin = "0.8.7"
mixinextras = "0.5.0"
mixinextras-range = "[0.5.0,)"
jsr305 = "3.0.2"
# Specific log4j version required by neoform
log4j = "2.22.1"
# Specific ow-asm version required by neoforge
ow-asm = "9.3"
kotlinevents = "v2.0"

# Plugins
plugin-dokka = "2.0.0"
plugin-mixin = "0.7.38"
plugin-loom = "1.13.6"
plugin-moddev = "2.0.120"
plugin-idea-ext = "1.3"

[libraries]
# Mods
# filloaxlib depends on various things, so define in build.gradle
modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }
# name depends on mc version, so define in build.gradle
# rconfig = { group = "com.teamresourceful.resourcefulconfig", name = "resourcefulconfig-common-", version.ref = "modmenu" }

# Mod compatibility
#lithostitched = { group = "maven.modrinth", name = "lithostitched", version.ref = "lithostitched" }
lithostitched-neoforge = { group = "maven.modrinth", name = "lithostitched", version.ref = "lithostitched-neoforge" }
lithostitched-fabric = { group = "maven.modrinth", name = "lithostitched", version.ref = "lithostitched-fabric" }
rctapi-fabric = { group = "curse.maven", name = "radical-cobblemon-trainers-api-1152792", version.ref = "rctapi-fabric" }
rctapi-neoforge = { group = "curse.maven", name = "radical-cobblemon-trainers-api-1152792", version.ref = "rctapi-neoforge" }
cobblemon-fabric = { group = "com.cobblemon", name = "fabric", version.ref = "cobblemon" }
cobblemon-neoforge = { group = "com.cobblemon", name = "neoforge", version.ref = "cobblemon" }

# Mixin
mixin = { group = "org.spongepowered", name = "mixin", version.ref = "mixin" }
mixinextras-common = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlin-datetime" }
kotlin-datetime-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime-jvm", version.ref = "kotlin-datetime" }

# Platform
fabric = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
kotlinforge = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "kotlinforge" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }

# Misc
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j" }
ow-asm = { group = "org.ow2.asm", name = "asm", version.ref = "ow-asm" }
kotlinevents = { group = "com.github.stuhlmeier", name = "kotlin-events", version.ref = "kotlinevents" }

# Plugin dependencies (for buildSrc)
plugin-kotlin-jvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
plugin-kotlin-serialization = { group = "org.jetbrains.kotlin", name = "kotlin-serialization", version.ref = "kotlin" }
plugin-dokka-javadoc = { group = "org.jetbrains.dokka-javadoc", name = "org.jetbrains.dokka-javadoc.gradle.plugin", version.ref = "plugin-dokka" }

[plugins]
# Kotlin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Platform
moddevgradle = { id = "net.neoforged.moddev", version.ref = "plugin-moddev" }
loom = { id = "fabric-loom", version.ref = "plugin-loom" }

# Misc
ideaext = { id = "org.jetbrains.gradle.plugin.idea-ext", version.ref = "plugin-idea-ext" }
mixin = { id = "org.spongepowered.mixin", version.ref = "plugin-mixin" }    # todo: rename to plugin-mixin to avoid confusion