name: Publish Test Release (1.20.6)
 
on:
  push:
    branches:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1  
        with:
          path: .github/workflows/release-count

      - name: Get release count
        id: get_release_count
        run: |
          if [ ! -f release-count.txt ]; then
            echo "10" > release-count.txt
          else
            current_count=$(cat release-count.txt)
            echo "$((current_count + 1))" > release-count.txt
          fi
          echo "RELEASE_COUNT=$(cat release-count.txt)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -Pmod_version='${{ env.RELEASE_COUNT }}'

      - name: "Replace test release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "test-release-1.20.6"
          prerelease: true
          title: "Current Test Release [${{ env.RELEASE_COUNT }}] - 1.20.6"
          files: |
            build/libs/*.jar