name: Publish on GitHub (Dev)
 
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9].*'

#Environment variables that can later be referenced using ${{ env.MINECRAFT_VERSION }}. These are useful for repeating information and allow for quick changes for new mod updates
env: 
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17                   
  RELEASE_NAME: Versione Indev
  GITHUB_TOKEN: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - name: Get the version
        id: get_version
        run: 'echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
        working-directory: "Mod"

      - name: Build
        run: ./gradlew clean build
        working-directory: "Mod"

      - name: Copy Workaround for Github Publish Subdir
        run: cp -rv build ../
        working-directory: "Mod"

      - name: Ls
        run: ls build/libs
        working-directory: "Mod"

      - name: Publish (GitHub dev)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"

          name: "Release ${{ steps.get_version.outputs.VERSION }}"                             
          version: "${{ steps.get_version.outputs.VERSION }}"
          version-type: release

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
        

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Publish (GitHub dev)
  #       uses: Kir-Antipov/mc-publish@v3.3
  #       with:
  #         github-tag: "indevRelease"
  #         github-token: "${{ secrets.PUBLISH_GITHUB_TOKEN }}"

  #         name: "${{env.RELEASE_NAME}}"                             
  #         version: "0.1.0"
  #         version-type: alpha

  #         loaders: fabric
  #         game-versions: "${{env.MINECRAFT_VERSION}}"
  #         java: "${{env.JAVA_VERSION}}"
