name: Publish Nightly Build (1.20.6)
 
on:
  push:
    branches:
      - 'test/**'
env:
  TEST_RELEASE_NUM: ${{ vars.TEST_RELEASE_NUM }}
  JAVA_VERSION: 21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print release num
        run: "echo Release num: ${{ env.TEST_RELEASE_NUM }}"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v1  

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -Pmod_version='1.20.6-nightly-${{ steps.date.outputs.date }}-${{ env.TEST_RELEASE_NUM }}'
        env:
          GROWSSETH_MUSIC_PW: ${{ secrets.MUSIC_PW }}

      - name: "Replace test release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN_GITHUB }}"
          automatic_release_tag: "nightly-release-1.20.6"
          prerelease: true
          title: "Nightly build [${{ steps.date.outputs.date }}-${{ env.TEST_RELEASE_NUM }}] - 1.20.6"
          files: |
            build/libs/*.jar
            build/egobalego-at-home/*.zip
            build/datapack/*.zip

      - name: Increment release count
        id: get_release_count
        run: echo "NEW_RELEASE_COUNT=$((${{ env.TEST_RELEASE_NUM }} + 1))" >> $GITHUB_OUTPUT

      - name: "Call API"
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.github.com/repos/filloax/ruins-of-growsseth/actions/variables/TEST_RELEASE_NUM
          method: "PATCH"
          headers: '{ 
              "Accept": "application/vnd.github+json",
              "X-GitHub-Api-Version": "2022-11-28"
            }'
          body: '{ "name": "TEST_RELEASE_NUM",  "value": "${{ steps.get_release_count.outputs.NEW_RELEASE_COUNT }}" }'
          timeout: 3000
          bearer-token: ${{ secrets.TOKEN_GITHUB }}
          retries: 3
