name: Release Mod (1.21)
 
on:
  push:
    branches:
      - 'release/1.21.0'
env:
  JAVA_VERSION: 21
  MC_VER: 1.21            # Main version
  MC_VER_EXTRA: 1.21.1    # Minor releases that are still compatible

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1  

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      
      - name: Get version from gradle
        id: get_version
        run: echo "VERSION=$(./gradlew modVersion | grep VERSION | awk -F'=' '{print $2}')" >> $GITHUB_OUTPUT
  
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GROWSSETH_MUSIC_PW: ${{ secrets.MUSIC_PW }}
      
      - name: Extract latest changelog
        id: changelog
        run: |
          latest_version=$(grep -m 1 -oP '(?<=##\s)\d+\.\d+\.\d+' CHANGELOG.md)
          latest_changelog=$(sed -n "/## $latest_version/,/## /p" CHANGELOG.md | sed '$d')
          echo "$latest_changelog" > latest_changelog.txt

      - uses: Kir-Antipov/mc-publish@v3.3
        id: mc_publish
        with:
          modrinth-token: ${{ secrets.TOKEN_MODRINTH }}
          curseforge-token: ${{ secrets.TOKEN_CURSEFORGE }}

          name: Ruins of Growsseth ${{ steps.get_version.outputs.VERSION }} for Minecraft ${{ env.MC_VER }}
          version-type: beta

          game-versions: |
            ${{ env.MC_VER }}
            ${{ env.MC_VER_EXTRA }}
          dependencies: |
            resourceful-config(required)
            fabric-language-kotlin(required)
            fabric-api(required)
            modmenu(recommended)
          java: 21

          changelog-file: latest_changelog.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Ruins of Growsseth ${{ steps.get_version.outputs.VERSION }} for Minecraft ${{ env.MC_VER }}
          body_path: latest_changelog.txt
          token: ${{ secrets.TOKEN_GITHUB }}
          make_latest: true
          tag_name: v${{ steps.get_version.outputs.VERSION }}-${{ env.MC_VER }}
          files: |
            build/libs/*.jar
            build/egobalego-at-home/*.zip
            build/datapack/*.zip
      
      