name: Release Mod (1.21)
 
on:
  push:
    branches:
      - 'release/1.21.0'
env:
  JAVA_VERSION: 21
  MC_VER: 1.21.1           # Main version
  MC_VER_EXTRA: 1.21.1     # Minor releases that are still compatible

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'pull_request'"
    runs-on: ubuntu-latest
    outputs:
      mod_version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4  

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      
      - name: Get version from gradle
        id: get_version
        run: echo "VERSION=$(./gradlew modVersion | grep VERSION | awk -F'=' '{print $2}')" >> $GITHUB_OUTPUT
  
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GROWSSETH_MUSIC_PW: ${{ secrets.MUSIC_PW }}
      
      - name: Extract latest changelog
        id: changelog
        run: |
          latest_version=$(grep -m 1 -oP '(?<=##\s)\d+\.\d+\.\d+' CHANGELOG.md)
          latest_changelog=$(sed -n "/## $latest_version/,/## /p" CHANGELOG.md | sed '$d')
          echo "$latest_changelog" > latest_changelog.txt

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            fabric/build/libs/*.jar
            neoforge/build/libs/*.jar
            base/build/libs/*.jar
            base/build/datapack/*.zip
            latest_changelog.txt
          retention-days: 30

  publish_platform:
    name: Publish (Platforms)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: neoforge
            name: Neoforge
            dependencies: |
              resourceful-config(required)
              kotlin-for-forge(required)
          - platform: fabric
            name: Fabric
            dependencies: |
              resourceful-config(required)
              fabric-language-kotlin(required)
              fabric-api(required)
              modmenu(recommended)
    steps:
      - uses: actions/checkout@v1

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          
      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3
        id: mc_publish_fabric
        with:
          modrinth-token: ${{ secrets.TOKEN_MODRINTH }}
          modrinth-id: 476XCS3C
          curseforge-token: ${{ secrets.TOKEN_CURSEFORGE }}
          curseforge-id: 1017555

          name: Ruins of Growsseth ${{ needs.build.outputs.mod_version }} for ${{ matrix.name }} + Minecraft ${{ env.MC_VER }}

          files: |
            ${{ matrix.platform }}/build/libs/*.jar
          game-versions: |
            ${{ env.MC_VER }}
            ${{ env.MC_VER_EXTRA }}
          dependencies: ${{ matrix.dependencies }}
          java: 21

          changelog-file: latest_changelog.txt

      - run: echo "Published ${{ matrix.name }}!"

  publish_github:
    name: Publish (GitHub)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Publish (GitHub)
        uses: softprops/action-gh-release@v2
        with:
          name: Ruins of Growsseth ${{ needs.build.outputs.mod_version }} for Minecraft ${{ env.MC_VER }}
          body_path: latest_changelog.txt
          token: ${{ secrets.TOKEN_GITHUB }}
          make_latest: true
          tag_name: v${{ needs.build.outputs.mod_version }}-${{ env.MC_VER }}
          files: |
            base/build/libs/*.jar
            neoforge/build/libs/*.jar
            fabric/build/libs/*.jar
            base/build/datapack/*.zip